Add storage queues
JupiterOne/graph-azure pull request #151
Opened 2020-09-03 16:14 UTC by ndowmon

Added `azure_storage_queue`
Added `azure_storage_account--HAS-->azure_storage_queue`

2020-09-03 16:46 UTC, ndowmon commented on src/steps/resource-manager/storage/client.ts
> +          const resources = await resourceEndpoint.list(
`StorageManagementClient.queue`, `.table`, `.container`, and `.fileShare` all require `resourceGroupName` and `storageAccountName` as args to the `.list()` method. 

I added this intermediate `iterateAllStorageAccountResources` that can be leveraged by all children/resources of `StorageAccount`

2020-09-03 17:59 UTC, ndowmon commented on src/steps/resource-manager/storage/client.ts
> +          if (err?.body?.code === 'FeatureNotSupportedForAccount') {
Since we iterate all storage accounts, but some storage accounts cannot contain certain types of data stores (e.g. storage account with `kind=BlobStorage` cannot contain `queues`), allow execution to continue and return no queues when `FeatureNotSupportedForAccount`

2020-09-03 18:07 UTC, aiwilliams requested changes

2020-09-03 18:07 UTC, aiwilliams commented on src/steps/resource-manager/storage/client.ts
> +        return serviceClient.blobContainers.listNext(nextLink);
I'm not 100% sure, but this line looks problematic because the containing function seems independent of the kind, but this is referencing `blobContainers`.

2020-09-03 18:07 UTC, aiwilliams commented on src/steps/resource-manager/storage/client.ts
> +    callback: (e: BlobContainer) => void | Promise<void>,
`BlobContainer`?

2020-09-03 18:07 UTC, aiwilliams commented on src/steps/resource-manager/storage/converters.ts
> + *   https://azure.microsoft.com/en-us/blog/announcing-default-encryption-for-azure-blobs-files-table-and-queue-storage/
Copypasta?

2020-09-03 18:46 UTC, ndowmon commented
@aiwilliams thanks for the review. Made requested changes, can you take another look?

2020-09-04 12:23 UTC, austinkelleher commented on src/steps/resource-manager/storage/client.ts
> +          if (err?.body?.code === 'FeatureNotSupportedForAccount') {
Is there a way that we can make this a bit more explicit so that we do not perform a bunch of API calls that we know will fail?

2020-09-04 17:01 UTC, austinkelleher approved these changes

2020-09-04 17:26 UTC, aiwilliams approved these changes
Looks great. So sorry to have missed that that Azure recording function was not used before! I had wondered at one point if there were a way to avoid that mistake. Seems like we might need to learn more about creating eslint rules. 😄

2020-09-04 17:49 UTC, merged