Add storage tables
JupiterOne/graph-azure pull request #152
Opened 2020-09-03 16:40 UTC by ndowmon

Added `azure_storage_table`
Added `azure_storage_account--HAS-->azure_storage_table`

2020-09-03 16:42 UTC, ndowmon commented on src/steps/resource-manager/storage/client.ts
> +              'OperationNotAllowedOnKind',
I encountered a different error code that's thrown when a `BlobStorage` account tries to iterate over `Table` records.

2020-09-03 16:47 UTC, ndowmon commented on src/steps/resource-manager/storage/constants.ts
> +  _class: ['DataStore'],
Not sure if `DataStore` is a good entity type here. Seemed more generic to me than `Database` but others may disagree. Open to suggestions.

Maybe there should be a `Table` entity class.

2020-09-03 18:12 UTC, aiwilliams requested changes

2020-09-03 18:12 UTC, aiwilliams commented on src/steps/resource-manager/storage/client.test.ts
> +    const resources: StorageQueue[] = [];
`StorageQueue`?

2020-09-03 18:12 UTC, aiwilliams commented on src/steps/resource-manager/storage/client.ts
> +              'OperationNotAllowedOnKind',
Hmm, wondering if this is because the function references `blobContainers`? See https://github.com/JupiterOne/graph-azure/pull/151#discussion_r483160140.

2020-09-03 18:12 UTC, aiwilliams commented on src/steps/resource-manager/storage/constants.ts
> +  _class: ['DataStore'],
I'd copy whatever AWS is doing for DynamoDB tables.

2020-09-03 18:51 UTC, ndowmon commented on src/steps/resource-manager/storage/constants.ts
> +  _class: ['DataStore'],
AWS uses `[ 'Database', 'DataStore' ]` - good tip.

2020-09-03 18:52 UTC, ndowmon commented on src/steps/resource-manager/storage/client.test.ts
> +    const resources: StorageQueue[] = [];
Good catch, thanks. Almost identical interfaces but still.

2020-09-03 18:54 UTC, ndowmon commented on src/steps/resource-manager/storage/client.ts
> +              'OperationNotAllowedOnKind',
This error is actually not called in the same branch that used `blobContainers`, but I did check after fixing and it still exists.

My guess is that whoever wrote the api for `StorageQueues` was different or just didn't share error code with whoever wrote it for `Tables`. Not sure. But I'm going to leave this as is since the error code is definitely showing up in my API calls.

2020-09-04 17:01 UTC, austinkelleher submitted a review, later dismissed

2020-09-04 17:28 UTC, aiwilliams submitted a review, later dismissed

2020-09-04 17:50 UTC, austinkelleher approved these changes

2020-09-04 18:28 UTC, merged