Feature/azure container instance
JupiterOne/graph-azure pull request #171
Opened 2020-10-05 01:58 UTC by KeionneDerousselle

# Acceptance Criteria
Map the entities and relationships from Azure Container Instance.

# What Changed?
1. Added the **Container Group** entity
    A container group is a collection of containers that get scheduled on the same host machine. The containers in a container group share a lifecycle, resources, local network, and storage volumes. 

    https://docs.microsoft.com/en-us/azure/container-instances/container-instances-container-groups#storage
    https://docs.microsoft.com/en-us/azure/container-instances/container-instances-overview

2. Added the **Container** entity
    The running containerized instance of the user's application.

3. Added the **Volume** entity
    By default, Azure Container Instances are stateless. You must mount a volume from an external store to persist state beyond the lifetime of the container.
    https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files

4. Added the **Resource Group** has **Container Group** relationship

5. Added the **Container Group** has **Container** relationship

6. Added the **Container Group** has **Volume** relationship

7. Added the **Container** connects **Volume** relationship

# Graph
![container-instance](https://user-images.githubusercontent.com/6044786/95033075-1e5b2a80-067a-11eb-990a-fd664ea82a95.png)

2020-10-05 15:08 UTC, ndowmon requested changes
@KeionneDerousselle Looks good! There's one additional relationship that I think needs to be created, I mentioned in a comment. I also posted some entity/relationship class changes.

2020-10-05 15:08 UTC, ndowmon commented on src/steps/resource-manager/container-instance/contants.ts
> +    _type: 'azure_volume',
I'm torn wondering whether this should be `azure_volume` or `azure_container_volume`... not sure if this volume is characteristically different than other volumes that could exist in azure. @aiwilliams any thoughts?

2020-10-05 15:08 UTC, ndowmon commented on src/steps/resource-manager/container-instance/converters.test.ts
> +        storageAccountName: 'keionnedj1dev',
It seems like there should also be a `azure_storage_share--HAS-->azure_volume` relationship here?

2020-10-05 15:23 UTC, KeionneDerousselle commented on src/steps/resource-manager/container-instance/contants.ts
> +    _type: 'azure_volume',
That makes sense. I can make that change.

2020-10-05 15:27 UTC, KeionneDerousselle commented on src/steps/resource-manager/container-instance/converters.test.ts
> +        storageAccountName: 'keionnedj1dev',
I thought that volume was using the storage share as its actual mechanism for storing. Would it make sense to say that the volume uses the storage share?

2020-10-05 15:27 UTC, KeionneDerousselle commented on src/steps/resource-manager/container-instance/contants.ts
> +    _class: RelationshipClass.CONNECTS,
👍

2020-10-05 15:59 UTC, ndowmon commented on src/steps/resource-manager/container-instance/converters.test.ts
> +        storageAccountName: 'keionnedj1dev',
Hm, that's a good point. Yeah, I think that the relationship you proposed makes sense.

2020-10-05 16:05 UTC, KeionneDerousselle commented on src/steps/resource-manager/container-instance/converters.test.ts
> +        storageAccountName: 'keionnedj1dev',
That might take me a while, the volumes returned as an array on the container group don't have an id. They only come back with a share name and the storage account name. I'll have to try to derive an id to find it in the tracked entities to create a relationship between the two.

2020-10-05 16:25 UTC, KeionneDerousselle commented on src/steps/resource-manager/container-instance/converters.test.ts
> +        storageAccountName: 'keionnedj1dev',
Also, volumes don't always use Azure File Shares. They can use Secrets, and empty directory, or a GitHub repo.

https://docs.microsoft.com/en-us/azure/container-instances/container-instances-container-groups#storage

Should I create entities and relationships for that as well?

2020-10-05 16:51 UTC, ndowmon commented on src/steps/resource-manager/container-instance/converters.test.ts
> +        storageAccountName: 'keionnedj1dev',
You can do something like this in `index.ts`-

```typescript
            container.volumeMounts?.forEach(async (volumeMount) => {
              const volumeKey = `${id}/volumes/${volumeMount.name}`;
              // Find the previously tracked volume so that we can record a relationship between the container and the volume
              const connectedVolumeEntity = await jobState.findEntity(
                volumeKey,
              );

              if (volumeMount.azureFile?.shareName !== undefined) {
                let storageShare: Entity;
                await jobState.iterateEntities({ _type: STORAGE_FILE_SHARE_ENTITY_METADATA._type },
                  (storageFileShare) => {
                    const fileShareRegex = 
                    const match = "/subscriptions/[^/]+/resource[G|g]roups/[^/]+/providers/Microsoft.Storage/storageAccounts/([^/]+)/fileServices/default/shares/([^/]+)"; 
                    const match = storageFileShare.id.match(fleShareRegex);
                    if (match) {
                      const [ _, storageAccountName, storageShareName ] = match;
                      if (storageAccountName === volumeMount.azureFile.shareName && storageShareName === volumeMount.azureFile.shareName) {
                        storageShare = storageFileShare;
                      }
                    }
                  }
                )
              }

              if (connectedVolumeEntity) {
                await jobState.addRelationship(
                  createDirectRelationship({
                    _class: RelationshipClass.USES,
                    from: containerEntity,
                    to: connectedVolumeEntity,
                    properties: volumeMount,
                  }),
                );
              }
            });
```

2020-10-05 17:32 UTC, aiwilliams commented on src/steps/resource-manager/container-instance/contants.ts
> +    _type: 'azure_volume',
The AWS integration has `aws_ebs_volume` for all block storage devices, no other `_type` value with "volume" in it. So, fwiw, seems reasonable to me to have all Azure storage volumes be a single type unless it can be argued that they really are very different things when provisioned/used by a container.

2020-10-05 17:39 UTC, aiwilliams commented on src/steps/resource-manager/container-instance/converters.test.ts
> +        storageAccountName: 'keionnedj1dev',
If you do `container.volumeMounts?.forEach(async (volumeMount) => {`, you'd have to `await` the `forEach`, which does not return a `Promise`. I tend to just use a `for/of` loop, like `for (const volumeMount of (container.volumeMounts? || []))` when there'll need to be an `async ()` in the loop.

2020-10-05 18:07 UTC, aiwilliams commented on src/steps/resource-manager/container-instance/types.ts
> +export type VolumeWithId = Volume & { id: string };
I think it would be nice to have comments that are in the code/functions to move to these types. This will allow folks to see the purpose of these types here, and well as when hovering over the types wherever they are referenced in the functions that receive them.

2020-10-05 18:07 UTC, aiwilliams commented on src/steps/resource-manager/container-instance/index.ts
> +              const volumeKey = `${id}/volumes/${volumeMount.name}`;
Hmm, these really are looking like volumes that exist solely for the container (`azure_container_volume`). Is there a way to view these volumes apart from the container that defines them?

2020-10-05 18:07 UTC, aiwilliams commented on src/steps/resource-manager/container-instance/index.ts
> +             */
This is the commentary that I think could be moved to the `ContainerWithId` type, which the `createContainerEntity` function receives. Perhaps there may also need to be docs on the `createContainerEntity` function. In any case, the point is, the commentary goes from being in this one place where the type and function are used to being on the type/function no matter where it ends up being used, and the editors are great with onHover doc visualization!

2020-10-05 21:31 UTC, KeionneDerousselle commented on src/steps/resource-manager/container-instance/index.ts
> +          containerGroup.containers.forEach(async (container) => {
I just didn't know this. You aren't misunderstanding anything lol, I was. I will fix this.

2020-10-05 21:32 UTC, KeionneDerousselle commented on src/steps/resource-manager/container-instance/client.test.ts
> +            image: 'microsoft/aci-helloworld:latest',
How can we tell, without an Id, whether the image is internal to the company (already ingested and tracked) or external (like the one in this example/line 68)?

2020-10-05 21:33 UTC, KeionneDerousselle commented on src/steps/resource-manager/container-instance/__snapshots__/converters.test.ts.snap
> +  "_type": "azure_container_volume",
I'm not sure. I don't think the volume we are representing is available outside of the container. It's just a way to map a drive to some external existing data source, I think. I might be misunderstanding something. Let's get on a call to discuss.

2020-10-06 20:09 UTC, KeionneDerousselle commented on src/steps/resource-manager/container-instance/contants.ts
> +    _type: 'azure_volume',
We discussed more about how the structure of data returns for Azure and decided that we would continue with the relationships we have. We discussed potentially removing the Container Volume entity in the future and linking the Container Group directly to the file share. We discussed moving that Volume data as properties on the Container Group uses File Share relationship. We would add the Container uses File Share relationship (essentially removing the Container Volume entity all together) and move the `volumeMount` data to the Container users File Share relationship.

2020-10-06 20:10 UTC, KeionneDerousselle commented on src/steps/resource-manager/container-instance/__snapshots__/converters.test.ts.snap
> +  "_type": "azure_container_volume",
We discussed more about how the structure of data returns for Azure and decided that we would continue with the relationships we have. We discussed potentially removing the Container Volume entity in the future and linking the Container Group directly to the file share. We discussed moving that Volume data as properties on the Container Group uses File Share relationship. We would add the Container uses File Share relationship (essentially removing the Container Volume entity altogether) and move the volumeMount data to the Container users File Share relationship.

2020-10-06 20:11 UTC, KeionneDerousselle commented on src/steps/resource-manager/container-instance/client.test.ts
> +            image: 'microsoft/aci-helloworld:latest',
We discussed adding this later because we are not ingesting images at the moment. We also don't know how Azure treats images. (Do image names refer to an image registered with Azure or in Docker?)

2020-10-06 20:12 UTC, KeionneDerousselle commented on src/steps/resource-manager/container-instance/index.ts
> +              const volumeKey = `${id}/volumes/${volumeMount.name}`;
We discussed more about how the structure of data returns for Azure and decided that we would continue with the relationships we have. We discussed potentially removing the Container Volume entity in the future and linking the Container Group directly to the file share. We discussed moving that Volume data as properties on the Container Group uses File Share relationship. We would add the Container uses File Share relationship (essentially removing the Container Volume entity all together) and move the volumeMount data to the Container users File Share relationship.

2020-10-06 20:38 UTC, ndowmon approved these changes

2020-10-07 15:48 UTC, aiwilliams approved these changes
Thanks @KeionneDerousselle & @ndowmon !

2020-10-07 16:11 UTC, merged