Add azure advisor
JupiterOne/graph-azure pull request #174
Opened 2020-10-12 20:15 UTC by ndowmon

Initial service ingestion for Azure Advisor, which ingests `azure_security_assessment` and `azure_advisor_recommendation`. 

An `azure_advisor_recommendation` can target any scope, including `subscription`, `resource_group` or any resource. A follow-on PR will add case-insensitive matching & custom matchers for validation.

This PR also enables an `executeLastSteps` mechanism that allows special steps (including those that can relate to any scope, such as `azure_advisor_recommendation` or `azure_role_assignment`) to execute after all other resources have been ingested.

2020-10-12 20:18 UTC, ndowmon commented on src/steps/resource-manager/advisor/index.ts
> +    );
Azure badly maims its own case-sensitive IDs when returning data from the `Recommendations` API. I'm working on a follow-on PR to expose a `findAzureEntity()` function that handles case-insensitive matching in these and other IDs.

2020-10-12 20:21 UTC, ndowmon commented on docs/jupiterone.md
> +| `ANY_SCOPE`                     | **HAS**               | `azure_advisor_recommendation`        |
I suggested in one of @erichs' recent PRs that maybe we could use an `UPPER_CASE` convention in `StepRelationshipMetadata` definitions to denote that the relationship could target (or be sourced from) many different `_type`s. Earlier, I used the convention of defining each entity that could be involved in the relationship (which is why there are so many `azure_role_assignment|ALLOWS|*` relationships in this table, even though it's an incomplete list.

2020-10-14 18:23 UTC, austinkelleher requested changes
This is awesome and is a great path for others to follow! I've noted a few things that I think we should look at to conform to the data-model. Let me know what you think.

2020-10-14 18:23 UTC, austinkelleher commented on src/steps/resource-manager/advisor/converters.ts
> +  data: ResourceRecommendationBase,
Should we also set the `updatedOn` field to `parseTimePropertyValue(data.lastUpdated)`?

2020-10-14 18:23 UTC, austinkelleher commented on src/steps/resource-manager/constants.ts
> +export const ANY_RESOURCE = 'ANY_RESOURCE';
Nice we should establish a pattern for our integration guide. Perhaps the SDK exposes a constant or something. Would be great if our docs produce a consistent format for this.

2020-10-14 18:23 UTC, austinkelleher commented on src/steps/resource-manager/security/converters.ts
> +        resourceDetailsSource:
Is there any value in ingesting the `OnPremiseResourceDetails`? 

```ts
/**
 * Details of the On Premise resource that was assessed
 */
export interface OnPremiseResourceDetails {
  /**
   * Polymorphic Discriminator
   */
  source: "OnPremise";
  /**
   * Azure resource Id of the workspace the machine is attached to
   */
  workspaceId: string;
  /**
   * The unique Id of the machine
   */
  vmuuid: string;
  /**
   * The oms agent Id installed on the machine
   */
  sourceComputerId: string;
  /**
   * The name of the machine
   */
  machineName: string;
}

/**
 * Contains the possible cases for ResourceDetails.
 */
export type ResourceDetailsUnion = ResourceDetails | OnPremiseResourceDetails | AzureResourceDetails;
```

2020-10-14 18:23 UTC, austinkelleher commented on src/steps/resource-manager/security/converters.ts
> +  data: SecurityAssessment,
Looks like `SecurityAssessment` can have metadata that could help us conform closer to data-model in some circumstances by leveraging `SecurityAssessmentMetadataProperties`. For example, there is a `category` property (and others that look potentially useful!):

```ts
/**
 * Describes properties of an assessment metadata.
 */
export interface SecurityAssessmentMetadataProperties {
  /**
   * User friendly display name of the assessment
   */
  displayName: string;
  /**
   * Azure resource ID of the policy definition that turns this assessment calculation on
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly policyDefinitionId?: string;
  /**
   * Human readable description of the assessment
   */
  description?: string;
  /**
   * Human readable description of what you should do to mitigate this security issue
   */
  remediationDescription?: string;
  category?: Category[];
  /**
   * The severity level of the assessment. Possible values include: 'Low', 'Medium', 'High'
   */
  severity: Severity;
  /**
   * The user impact of the assessment. Possible values include: 'Low', 'Moderate', 'High'
   */
  userImpact?: UserImpact;
  /**
   * The implementation effort required to remediate this assessment. Possible values include:
   * 'Low', 'Moderate', 'High'
   */
  implementationEffort?: ImplementationEffort;
  threats?: Threats[];
  /**
   * True if this assessment is in preview release status
   */
  preview?: boolean;
  /**
   * BuiltIn if the assessment based on built-in Azure Policy definition, Custom if the assessment
   * based on custom Azure Policy definition. Possible values include: 'BuiltIn', 'CustomPolicy',
   * 'CustomerManaged', 'VerifiedPartner'
   */
  assessmentType: AssessmentType;
  partnerData?: SecurityAssessmentMetadataPartnerData;
}
```

2020-10-14 18:23 UTC, austinkelleher commented on src/steps/resource-manager/security/converters.ts
> +        statusCode: data.status.code,
Perhaps we should consider adding a `status` property to the data model in the future. Seems reasonable that the "status" of an assessment would be something that we could expect on assessments and "unknown" by default or something. Thoughts? cc @erkangz

2020-10-15 17:46 UTC, ndowmon commented on src/steps/resource-manager/security/converters.ts
> +  data: SecurityAssessment,
Thanks, good thinking looking at these types. I added some converters to auto convert both `metadata` and `resourceDetails`.

2020-10-16 12:21 UTC, austinkelleher approved these changes

2020-10-16 12:21 UTC, austinkelleher commented
Looks good, but conflicts.

2020-10-19 16:04 UTC, austinkelleher approved these changes

2020-10-19 16:04 UTC, merged