Feature/azure policy
JupiterOne/graph-azure pull request #191
Opened 2020-10-29 22:15 UTC by KeionneDerousselle

# Acceptance Criteria

# What Changed?
1. Added the **Policy Assignment** entity, of type **azure_policy_assignment**, and schema **ControlPolicy**.

    Azure Policy provides a way to enforce standards and compliance at-scale for an organization. It provides a compliance dashboard and allows you to drill down to specific Azure resources and policies. Not only does it offer insights, but you can also remediate issues in bulk and automatically apply policies and remediation to any new resources.

    Azure policy evaluates and applies business rules, defined in JSON format, to Azure resources. These business rules are known as Azure Policy Definitions. These rules can be applied to a Management Group, Azure Subscription, Azure Resource Group, or Azure Resource. 

    [Azure Management Group](https://docs.microsoft.com/en-us/azure/governance/management-groups/overview) - a grouping of multiple Azure Subscriptions. One such example is creating a Management Group for specific departments in your organization. From there, each department can have multiple Azure Subscriptions within its Management Group. 

# Decisions Made

# Out of Scope

# Graph

2020-10-30 13:36 UTC, aiwilliams requested changes

2020-10-30 13:36 UTC, aiwilliams commented on src/steps/resource-manager/policy/__snapshots__/converters.test.ts.snap
> +  "metadata.updatedOn": "2020-10-29T17:42:36.1625526Z",
I think we should get these moved directly to the entity: `"_class": "ControlPolicy", "createdOn": number, "createdBy": string, ... etc`. We should populate created/update timestamps from the source anytime that data is available.

Can the `createdBy` etc. values be used to build a relationship to a principal? I think we should create an Issue for those relationships to do it later and hopefully driven by other CIS Benchmark questions. 😄

2020-10-30 13:36 UTC, aiwilliams commented on src/steps/resource-manager/policy/client.test.ts
> +     * Security Center -> Security Policy -> <Your Subscription> -> Security center default policy -> View effective policy -> ASC Default (subscription: <Your Subscription Id>)
❤️  the details!

2020-10-30 13:36 UTC, aiwilliams commented on src/steps/resource-manager/policy/index.ts
> +              _type: 'ANY_SCOPE_has_policy_assignment',
This could be `PolicyRelationships.ANY_RESOURCE_POLICY_ASSIGNMENT._type` to allow for a single point of modification.

2020-10-30 13:36 UTC, aiwilliams commented on src/steps/resource-manager/policy/constants.ts
> +   * it might cause issues down the road.
How about `azure_resource_has_policy_assignment`? I don't think I've seen any uppercase chars in `_type` values, and I think there are various parts fo the system that count on snake case for `_type` values. Also, since these are vendor-specific relationships. they should have the vendor id as a prefix.

2020-10-30 13:36 UTC, aiwilliams commented on src/steps/resource-manager/policy/helpers.test.ts
> +describe('flatten', () => {
Would love to see a PR for the SDK to have this alongside `convertProperties`, perhaps as `flattenObjectPropertyValue` (for symmetry with `convertTimePropertyValue`), so that folks don't attempt to flatten everything, but use it as:

```
  displayName: data.name,
  ...flattenObjectPropertyValue(data.parameters)
```

2020-10-30 13:36 UTC, aiwilliams commented on src/steps/resource-manager/policy/helpers.ts
> +      const time = parseTimePropertyValue(value);
💯

2020-10-30 13:59 UTC, austinkelleher submitted a review, later dismissed
Awesome! Thanks for your work on this. Looks good to me. Only left a few minor comments/questions.

2020-10-30 13:59 UTC, austinkelleher commented on src/steps/resource-manager/policy/index.ts
> +    await jobState.addEntity(policyAssignmentEntity);
This is pretty minor, but it's worth noting that `addEntity` now returns the entity, so you can change this to:

```ts
const policyAssignmentEntity = await jobState.addEntity(
  createPolicyAssignmentEntity(
     webLinker,
     policyAssignment,
  )
);
```

Also, I generally prefer early returns over nested conditions. I think it also helps simplify code and prevents a bunch of indentation. What do you think of changing this block of code to the following:

```ts
export async function fetchPolicyAssignments(
  executionContext: IntegrationStepContext,
): Promise<void> {
  const { instance, logger, jobState } = executionContext;
  const accountEntity = await jobState.getData<Entity>(ACCOUNT_ENTITY_TYPE);
  const webLinker = createAzureWebLinker(accountEntity.defaultDomain as string);
  const client = new AzurePolicyClient(instance.config, logger);

  await client.iteratePolicyAssignments(async (policyAssignment) => {
    const policyAssignmentEntity = await jobState.addEntity(
      createPolicyAssignmentEntity(
         webLinker,
         policyAssignment,
      )
    );

    const { scope } = policyAssignment;
    if (!scope) return;

    const scopeEntity = await jobState.findEntity(scope);
    if (!scopeEntity) return;

    await jobState.addRelationship(
      createDirectRelationship({
        _class: RelationshipClass.HAS,
        from: scopeEntity,
        to: policyAssignmentEntity,
        /**
         * NOTE: Azure Management Groups, Azure Subscriptions, Azure Resource Groups, and Azure Resources can all have Azure Policy Assignments.
         * We currently don't ingest Management Groups, but we do ingest Subscriptions, Resource Groups, and some Resources
         * We've chosen to represent the relationship as ANY_SCOPE has a Policy Assignment.
         * This is because we want the relationship metadata to line up with the actual ingested relationships.
         * If we say that we expect ANY_SCOPE_had_policy_assignment and instead generate that a azure_storage_account_has_policy_assignment,
         * it might cause issues down the road.
         */
        properties: {
          _type: 'ANY_SCOPE_has_policy_assignment',
        },
      }),
    );
  });
}
```

2020-10-30 13:59 UTC, austinkelleher commented on src/steps/resource-manager/policy/helpers.ts
> +export type FlattenObjectOptions = {
It doesn't seem like we are using any of these options right now. Is that true?

2020-10-30 13:59 UTC, austinkelleher commented on src/steps/resource-manager/policy/helpers.ts
> +export function flatten(
Thanks for thinking about this. We should consider putting this into the SDK once we've proven it out!

2020-10-30 14:07 UTC, ndowmon commented on src/steps/resource-manager/policy/constants.ts
> +   * it might cause issues down the road.
@aiwilliams this is a convention that I used recently in the Azure `advisor` service. I chose uppercase to make these one-to-many type relationships easily differentiated in `jupiterone.md` files. Perhaps the `sourceType` property can still be uppercase for the sake of the docs, but we can do something different with the actual type (such as `azure_resource_has_policy_assignment`, as you noted).

2020-10-30 14:57 UTC, ndowmon reviewed
This looks good! Thanks!

2020-10-30 14:57 UTC, ndowmon commented on src/steps/resource-manager/policy/client.ts
> +      },
If there are no arguments to the `serviceClient.policyAssignments.list()` function, you can simply pass as below:

```suggestion
      resourceEndpoint: serviceClient.policyAssignment,
```

2020-10-30 14:57 UTC, ndowmon commented on src/steps/resource-manager/policy/helpers.test.ts
> +describe('flatten', () => {
I wonder if some of these can be added to the `ConvertPropertiesOptions`: https://github.com/JupiterOne/sdk/blob/master/packages/integration-sdk-core/src/data/converters.ts#L35

2020-10-30 14:57 UTC, ndowmon commented on src/steps/resource-manager/policy/helpers.ts
> +export type FlattenObjectOptions = {
It looks like these properties (or at least some of them) come from the `ConvertPropertiesOptions` interface... https://github.com/JupiterOne/sdk/blob/master/packages/integration-sdk-core/src/data/converters.ts#L35

2020-10-30 22:22 UTC, KeionneDerousselle commented on src/steps/resource-manager/policy/helpers.test.ts
> +describe('flatten', () => {
https://github.com/JupiterOne/sdk/issues/369

2020-10-30 22:23 UTC, KeionneDerousselle commented on src/steps/resource-manager/policy/helpers.ts
> +export type FlattenObjectOptions = {
https://github.com/JupiterOne/sdk/issues/369

2020-10-30 22:23 UTC, KeionneDerousselle commented on src/steps/resource-manager/policy/helpers.ts
> +export function flatten(
https://github.com/JupiterOne/sdk/issues/369

2020-11-02 16:38 UTC, ndowmon requested changes

2020-11-02 16:38 UTC, ndowmon commented on src/steps/resource-manager/policy/converters.ts
> +      source: pa,
I think source should still be `data`, including the metadata. The metadata property ought to be available in raw data.

2020-11-02 17:04 UTC, KeionneDerousselle commented on src/steps/resource-manager/policy/converters.ts
> +      source: pa,
When I had that, I got "duplicate" keys. 
```
{
  'metadata.assignnedBy': '',
  'metadata.createdOn': '',
  createdOn: '',

}
```

2020-11-02 17:06 UTC, KeionneDerousselle commented on src/steps/resource-manager/policy/converters.ts
> +      source: pa,
Is that what we want? I thought @aiwilliams wanted us to pull those properties to the top level of the entity.

2020-11-02 18:26 UTC, aiwilliams commented on src/steps/resource-manager/policy/converters.ts
> +      source: pa,
I don't think we want that to happen. Is the `source.metadata` being transferred "automatically" by something in `createIntegrationEntity()`?

2020-11-02 18:31 UTC, KeionneDerousselle commented on src/steps/resource-manager/policy/converters.ts
> +      source: pa,
I'm not sure if assigning `source` to `data` or the `assign: { ...flatten(data), ...)` was the culprit. I thought we just wanted to specifically peel those props off and move them to the very top so I spread them on at the root level at the end of the object.

2020-11-02 18:34 UTC, KeionneDerousselle commented on src/steps/resource-manager/policy/converters.ts
> +      source: pa,
I originally had:
```typescript
export function createPolicyAssignmentEntity(
  webLinker: AzureWebLinker,
  data: PolicyAssignment,
): Entity {
  return createIntegrationEntity({
    entityData: {
      source: data,
      assign: {
        ...flatten(data),
        _key: pa.id,
        _type: PolicyEntities.POLICY_ASSIGNMENT._type,
        _class: PolicyEntities.POLICY_ASSIGNMENT._class,
        id: pa.id,
        name: pa.displayName,
        webLink: webLinker.portalResourceUrl(pa.id),
        scope: pa.scope,
        policyDefinitionId: pa.policyDefinitionId,
      },
    },
  });
}
```
I then changed it to:
```typescript
export function createPolicyAssignmentEntity(
  webLinker: AzureWebLinker,
  data: PolicyAssignment,
): Entity {
  const { metadata, ...pa } = data;
  const assignedBy = metadata?.assignedBy;
  const createdOn = parseTimePropertyValue(metadata?.createdOn);
  const updatedOn = parseTimePropertyValue(metadata?.updatedOn);
  const createdBy = metadata?.createdBy;
  const updatedBy = metadata?.updatedBy;

  return createIntegrationEntity({
    entityData: {
      source: pa, // to remove metadata
      assign: {
        ...flatten(pa), // to remove metadata
        _key: pa.id,
        _type: PolicyEntities.POLICY_ASSIGNMENT._type,
        _class: PolicyEntities.POLICY_ASSIGNMENT._class,
        id: pa.id,
        name: pa.displayName,
        webLink: webLinker.portalResourceUrl(pa.id),
        scope: pa.scope,
        policyDefinitionId: pa.policyDefinitionId,
        ...(assignedBy && { assignedBy }),
        ...(createdBy && { createdBy }),
        ...(createdOn && { createdOn }),
        ...(updatedBy && { updatedBy }),
        ...(updatedOn && { updatedOn }),
      },
    },
  });
}
```

2020-11-02 18:35 UTC, KeionneDerousselle commented on src/steps/resource-manager/policy/converters.ts
> +      source: pa,
Are we saying we just want to keep `source: data` to have the original data as the source and leave `assign: { ...flatten(pa), ... }`?

2020-11-02 18:47 UTC, ndowmon commented on src/steps/resource-manager/policy/converters.ts
> +      source: pa,
@KeionneDerousselle yes, you should just change `source: pa` back to `source: data`. The change you made for `...flatten(pa)` was the only thing that needed to change. This way, the entity properties include `createdOn`, etc instead of `metadata.createdOn`, but the `_rawData` of the entity will include `metadata: { createdOn: ... }`

2020-11-02 18:57 UTC, ndowmon approved these changes

2020-11-02 19:06 UTC, aiwilliams approved these changes

2020-11-02 20:15 UTC, austinkelleher approved these changes

2020-11-02 20:16 UTC, merged