Feature/azure monitor log profiles
JupiterOne/graph-azure pull request #195
Opened 2020-11-06 22:42 UTC by KeionneDerousselle

# Acceptance Criteria
- Ingest [Azure Monitor Log Profile](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/activity-log#legacy-collection-methods)
    - Log Profiles are the legacy method for sending the Activity Log to Azure Storage or Azure Event Hubs. The Activity Log captures all management activities performed on a subscription. By default, Activity Logs are only retained for 90 days. Historically, Log Profiles were used to make sure that all subscription related logs were retained for a longer duration. You can only have one Log Profile per Azure Subscription.

- 5.1.1 Ensure that a Log Profile exists (Scored)
    - The CIS requirements say to ensure that at least one Log Profile exists for a subscription.

- 5.1.2 Ensure that Activity Log Retention is set 365 days or greater (Scored)
    - This CIS requirement is to ensure that logs are retained for at least a year if not forever. The Log Profile seems to have a `retentionPolicy` property which is an object containing whether or not retention is enabled and if so, how many days it is enabled. We flattened this object using dot notation and put it on the **Log Profile** entity.

- 5.1.3 Ensure audit profile captures all the activities (Scored)
    - This CIS requirement is to ensure that Activity Logs are captured when any ‘write’, ‘delete’, or ‘action’ activities are performed on the Azure Subscription. This data is returned via a categories property, which is an array of strings. We put the `categories` property on the **Log Profile** entity.

- 5.1.4 Ensure the log profile captures activity logs for all regions including global (Scored)
    - This CIS requirement is to ensure that any activities that happen in any Azure supported region are logged. This data is returned via a locations string array on the Log Profile. The `locations` array was put on the **Log Profile** entity.

- 5.1.5 Ensure the storage container storing the activity logs is not publicly accessible (Scored)
    - This information is not on the **Log Profile** and thus won’t come from the @azure/arm-monitor client, but is instead stored on the **Storage Account**. We added the `allowBlobPublicAccess` to the **Storage Account** entity.

- 5.1.6 Ensure the storage account containing the container with activity logs is encrypted with BYOK (Use Your Own Key) (Scored)
    -  This CIS requirement aims to ensure that the logs stored in the Storage Account are encrypted with your own encryption key. By default, they are not. This information is not on the Log Profile and thus won’t come from the @azure/arm-monitor client, but is instead stored on the Storage Account. We added the `encyrption.keySource` and `encryption.keyVaultProperties` to the **Storage Account** entity. `keySource` should be set to `Microsoft.Keyvault` and `keyVaultProperties` should not be null. 

# What Changed?
- Added the **Azure Monitor Log Profile** entity
- Added the **Azure Subscription** has **Monitor Log Profile** relationship
- Added the **Azure Monitor Log Profile** uses **Azure Storage Account** relationship
- Added the **allowBlobPublicAccess** property to the **Azure Storage Account** entity
- Added certain properties on the **encryption** object to the **Azure Storage Account** entity 
    - `encryption.keySource`
    - `encryption.keyValueProperties.keyName`
    -  `encryption.keyValueProperties.keyVaultUri`
    - `encryption.keyValueProperties.keyVersion`

# Decisions Made
- Any objects we needed to capture on the entities would be flattened with dot notation

- If an **Azure Monitor Log Profile** had a defined `storageAccountId`, we would associate it, if possible, with any known ingested **Azure Storage Accounts** by creating a `uses` relationship. (i.e. **Azure Monitor Log Profile** `uses` **Azure Storage Account**)

- Although **Azure Monitor Log Profiles** are not the preferred way to retain **Azure Activity Logs**, we decided to ingest this data for now and later ingest **Azure Diagnostic Settings**

# Out of Scope
- If an **Azure Monitor Log Profile** had a defined `serviceBusRuleId`, we would not associate it with any **Azure EventHubs**. This is because we are not currently ingesting **Azure Eventhub** and creating any such relationships does not help to answer any CIS benchmark questions at this time.

# Graph

2020-11-10 14:27 UTC, aiwilliams commented on src/steps/resource-manager/storage/converters.test.ts
> +      'encryption.keyValueProperties.keyVersion': 'version',
These look like unrelated changes that are not listed in the `CHANGELOG.md`. Also, what do you think about flattening as:
```
'encryption.keySource': 'Microsoft.Keyvault',
'encryption.keyName': 'test',
'encryption.keyVaultUri': 'testUri',
'encryption.keyVersion': 'version',
```

2020-11-10 14:43 UTC, ndowmon requested changes
Thanks for your work on this one @KeionneDerousselle! I added a couple requests here.

2020-11-10 14:43 UTC, ndowmon commented on src/steps/resource-manager/monitor/converters.ts
> +        'retentionPolicy.days': data.retentionPolicy.days,
Is `data.retentionPolicy` nullable? If so I think you'll have to add optional chaining here.

```suggestion
        'retentionPolicy.enabled': data.retentionPolicy?.enabled,
        'retentionPolicy.days': data.retentionPolicy?.days,
```

2020-11-10 14:43 UTC, ndowmon commented on src/steps/resource-manager/storage/converters.test.ts
> +        keyVaultUri: 'testUri',
If `keyVaultProperties.keyVaultUri` is not `undefined`, it should create a relationship to a `keyVault`.

2020-11-10 14:43 UTC, ndowmon commented on src/steps/resource-manager/storage/converters.test.ts
> +      'encryption.keyValueProperties.keyVersion': 'version',
@aiwilliams they're related:

>5.1.6 Ensure the storage account containing the container with activity logs is encrypted with BYOK (Use Your Own Key) (Scored)

2020-11-10 17:00 UTC, KeionneDerousselle commented on src/steps/resource-manager/storage/converters.test.ts
> +      'encryption.keyValueProperties.keyVersion': 'version',
@aiwilliams The CIS Benchmark is based on the `keyVauleProperties` key name. It says to ensure the value of `keyValueProperties` is not null. If we remove it, will it make it harder to query it?

2020-11-10 17:06 UTC, KeionneDerousselle commented on src/steps/resource-manager/monitor/converters.ts
> +        'retentionPolicy.days': data.retentionPolicy.days,
According to the typings, it is not nullable.
<img width="1069" alt="Screen Shot 2020-11-10 at 10 05 23 AM" src="https://user-images.githubusercontent.com/6044786/98706653-52da9a00-233c-11eb-94e1-40601b1858e8.png">

2020-11-10 17:09 UTC, KeionneDerousselle commented on src/steps/resource-manager/storage/converters.test.ts
> +        keyVaultUri: 'testUri',
I couldn't find any information about whether or not this URI is the id of a KeyVault we are ingesting. Also, it didn't seem to answer any of the CIS Benchmark questions so I didn't include that in the initial scope. If we want to include that, I can continue to search for an example of what this URI looks like/points to.

2020-11-10 18:27 UTC, aiwilliams commented on src/steps/resource-manager/storage/converters.test.ts
> +      'encryption.keyValueProperties.keyVersion': 'version',
Gotcha. Probably best to leave as you've done it then. Thanks!

2020-11-10 18:28 UTC, aiwilliams commented on src/steps/resource-manager/storage/converters.test.ts
> +        keyVaultUri: 'testUri',
Probably now is the best time to resolve the question, and add a comment about why it cannot be used to build a relationship.

2020-11-11 21:43 UTC, ndowmon commented on src/steps/resource-manager/storage/index.test.ts
> +              },
Hey @KeionneDerousselle it would be great if you could make this a little safer using Azure types. Something like:

```typescript
import { Vault } from '@azure/arm-keyvault/esm/models';

// ...

const vault: Vault = {
  properties: {
    vaultUri: `https://${devName}-j1dev.vault.azure.net`,
  }
};

// ...

const context = createMockAzureStepExecutionContext({
  instanceConfig,
  entities: [
    {
      _class: ['Service'],
      _type: 'azure_keyvault_service',
      _key: `/subscriptions/${instanceConfig.subscriptionId}/resourceGroups/j1dev/providers/Microsoft.KeyVault/vaults/${devName}-j1dev`,
      id: `/subscriptions/${instanceConfig.subscriptionId}/resourceGroups/j1dev/providers/Microsoft.KeyVault/vaults/${devName}-j1dev`,
      name: `${devName}-j1dev`,
      _rawData: [
        {
          name: `${devName}-j1dev`,
          rawData: vault,
        },
      ],
    },
  ],
// ...
```

2020-11-11 22:16 UTC, ndowmon approved these changes
Thank you!

2020-11-11 22:54 UTC, aiwilliams approved these changes

2020-11-11 22:54 UTC, aiwilliams commented on src/steps/resource-manager/storage/index.test.ts
> +   */
Thank you!

2020-11-16 21:45 UTC, merged