Feature/diagnostic settings
JupiterOne/graph-azure pull request #199
Opened 2020-12-07 21:50 UTC by KeionneDerousselle

# Acceptance Criteria
- Ingest [Azure Monitor Diagnostic Settings](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-settings)
    - Diagnostic Settings are the new way to send platform logs, including the Azure Activity Log and resource logs, and metrics to different destinations. It should not be used in tandem with Log Profile. Each Azure resource has its own diagnostic settings. These settings define the categories or types of metrics and logs that should be sent somewhere, and one or more destinations to send the logs and metrics. Currently, you can send metrics and logs to Log Analytics workspace, Event Hubs, and Azure Storage. 

- 5.1.5 Ensure that logging for Azure KeyVault is 'Enabled' (Automated)
    - This benchmark aims to ensure that AuditEvent logging is enabled for Key Vault instances. This ensures that interactions with Key Vaults are logged and available. This information is available in the array of LogSettings on the returned Diagnostic Setting object(s) for a Key Vault. The CIS Benchmark documentation says to make sure that ‘category’, ‘days’, and ‘storageAccountId’ are all set.

# What Changed?
- Added the **Azure Diagnostic Log Setting** entity
- Added the **Azure Diagnostic Metric Setting** entity
- Added the **Azure Resource** has **Azure Diagnostic Log Setting** relationship
- Added the **Azure Resource** had **Azure Diagnostic Metric Setting** relationship
- Added the **Azure Diagnostic Log Setting** uses **Azure Storage Account** relationship
- Added the **Azure Diagnostic Metric Setting** uses **Azure Storage Account** relationship

# Decisions Made
- Currently, Log and Metric Settings appear as arrays of objects on the **Azure Diagnostic Settings** returned for a given resource. Because querying these arrays of objects as JSON to answer the CIS benchmarks would be difficult, we decided to create each of these objects as their own entity.

- Log Settings and Metric Settings did not have ids, so we created our own to use as an entity key. There were no properties on these objects that uniquely identified them from other Log or Metrics Settings in the array. Therefore, we created a composite identifier. This identifier is made up of the id of the setting's parent object, the **Azure Diagnostic Settings**, and the properties on the Log or Metric Setting itself. 
    - The id of an Azure Diagnostic Log Setting entity should look like: `${diagnosticSettings.id}/logs/${category}/${enabled}/${retentionPolicy?.days}/${retentionPolicy?.enabled}`
    - The id of an Azure Diagnostic Metric Setting entity should look like : `${diagnosticSettings.id}/metrics/${category}/${enabled}/${timeGrain}/${retentionPolicy?.days}/${retentionPolicy?.enabled}`

- The list() function on the Diagnostic Settings endpoint does not return all Diagnostic Settings for an Azure Subscription. All list() functions require that you pass them an Id of the resource that you would like to get a list of Diagnostic Settings for. This means that you have to have the Id of the resource that you want Diagnostic Settings for before making this call. Knowing this, we decided to first get the **Azure Diagnostic Settings** for an **Azure Key Vault**. We will iterate on this later to make sure we are getting the **Azure Diagnostic Settings** for [all Azure resources that support **Diagnostic Settings**](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/resource-logs-categories#microsoftsqlserversdatabases).
    - We discussed potentially making a module, change to the Client class, or baking some automated process into the architecture to collect **Diagnostic Settings** for a resource. This would be preferable to manually retrieving **Diagnostic Settings** for each resource that supports it, especially because the number of supported resources change.

# Out of Scope
- Although **Diagnostic Log Settings** can configure a **Log Analytic** workspace that logs should be stored in, we did not create a relationship between **Diagnostic Log Settings** and **Log Analytic** workspaces. This is because we are not currently ingesting **Log Analytics**.

- Although **Diagnostic Metric Settings** can configure a **Log Analytic** workspace that logs should be stored in, we did not create a relationship between **Diagnostic Metric Settings** and **Log Analytic** workspaces. This is because we are not currently ingesting **Log Analytics**.

- Although **Diagnostic Log Settings** can configure an **Event Hub** that logs should be stored in, we did not create a relationship between **Diagnostic Log Settings** and **Event Hubs**. This is because we are not currently ingesting **Event Hubs**.

- Although **Diagnostic Metric Settings** can configure an **Event Hub** that logs should be stored in, we did not create a relationship between **Diagnostic Metric Settings** and **Event Hubs**. This is because we are not currently ingesting **Event Hubs**.

- We decided to first get the **Azure Diagnostic Settings** for an **Azure Key Vault**. We will iterate on this later to make sure we are getting the **Azure Diagnostic Settings** for [all Azure resources that support **Diagnostic Settings**](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/resource-logs-categories#microsoftsqlserversdatabases).

# Graph
<img width="1417" alt="Screen Shot 2020-12-07 at 2 34 32 PM" src="https://user-images.githubusercontent.com/6044786/101409736-878a3480-389b-11eb-84c7-81ca1e194a42.png">
<img width="977" alt="Screen Shot 2020-12-07 at 2 33 38 PM" src="https://user-images.githubusercontent.com/6044786/101409747-8bb65200-389b-11eb-98f2-f5323b2615c3.png">

2020-12-07 21:57 UTC, KeionneDerousselle commented on terraform/main.tf
> +    key_vault {
There was a change released to Key Vaults in Dec 2020. This change automatically enabled soft deletes of key vaults, because of this, we needed to tell terraform to restore soft-deleted key vaults that were torn down. You can currently create Key Vaults that are not setup to soft delete when destroyed, but this feature will be gone soon.

2020-12-07 22:00 UTC, KeionneDerousselle commented on terraform/keyvault.tf
> +  soft_delete_enabled         = true
I added this because the ability to disable soft delete will be gone soon. I did set the number of days to retain a soft deleted Key Vault to the lowest possible (7).

2020-12-07 22:02 UTC, KeionneDerousselle commented on terraform/main.tf
> +      purge_soft_delete_on_destroy = true
`purge_soft_delete_on_destroy` seems like the opposite of `recover_soft_deleted_key_vaults`. I'm not really sure why this combination of settings worked. I wasn't able to get it working (able to destroy and apply back to back) without both these settings set to true.

2020-12-07 22:03 UTC, KeionneDerousselle commented on src/steps/resource-manager/monitor/constants.ts
> +    sourceType: ANY_RESOURCE,
What's the different between `ANY_RESOURCE` and `ANY_SCOPE`, @ndowmon?

2020-12-07 22:05 UTC, KeionneDerousselle commented on src/steps/resource-manager/monitor/client.ts
> +                new DiagnosticSettingsListResponse(
The return type of the endpoint was not castable to type `ResourceListResponse`, so I had to create a return type that was.

2020-12-08 20:13 UTC, ndowmon commented on src/steps/resource-manager/monitor/constants.ts
> +    sourceType: ANY_RESOURCE,
`ANY_SCOPE` ought to include non-resource scopes such as `subscription` or `resourceGroup`.

2020-12-08 23:17 UTC, ndowmon requested changes
Hey @KeionneDerousselle this is an awesome first pass. I didn't even fully realize the complexity of these entities and relationships.

I have added a ton of feedback to this PR. It would be great to find some time to catch up tomorrow about this! Hit me up to schedule some time once you've read this over.

2020-12-08 23:17 UTC, ndowmon commented on src/steps/resource-manager/monitor/diagnostic-settings.ts
> +async function createEntitiesAndRelationships(
I would probably make this function more explicit about what it does.

2020-12-08 23:17 UTC, ndowmon commented on src/steps/resource-manager/monitor/diagnostic-settings.ts
> +];
We should chat about a good way to set up some of these maps. Also wondering if all of the interfaces are necessary.

2020-12-08 23:17 UTC, ndowmon commented on src/steps/resource-manager/monitor/converters.ts
> +}
These converters have me a little confused. It seems like there is one `DiagnosticSettingsResource` that contains an array of `MetricSettings` and `LogSettings`. 

If that's true, shouldn't there just be a `azure_diagnostic_settings` entity with all of these properties? And Then an `azure_diagnostic_settings_metrics` entity with the information about the `MetricSettings` and an `azure_diagnostic_settings_logs` entity with information about the `LogSettings`?

I would also expect the relationships to storage account to relate to `azure_diagnostic_settings`, not the `metrics` or `logs`.

2020-12-09 17:32 UTC, KeionneDerousselle commented on src/steps/resource-manager/monitor/constants.ts
> +    sourceType: ANY_RESOURCE,
I think we should maybe use `ANY_SCOPE` then. I think you can have Diagnostic Settings on subscriptions (i.e. replacing Log Profiles)

2020-12-09 17:33 UTC, KeionneDerousselle commented on terraform/keyvault.tf
> +  name                     = "j1devkeyvaultdiagsetstrg"
The unique identifier is a good point. Also, no we don't need to create a new resource group or storage account. I usually do to be able to have separate unaffected environments that can be stood up on their own, but in this case it costs money...sooo....I'll use the existing resources :)

2020-12-09 17:35 UTC, KeionneDerousselle commented on terraform/monitor.tf
> +}
I created both of those so that I can have Key Vault tests, and tests that test the generic log to get diagnostic settings. I wasn't sure how to unit test it without the current recording setup we have now.

2020-12-09 17:35 UTC, KeionneDerousselle commented on src/steps/resource-manager/monitor/diagnostic-settings.ts
> +import {
Thanks. I will make that change.

2020-12-09 17:36 UTC, KeionneDerousselle commented on src/steps/resource-manager/monitor/diagnostic-settings.ts
> +import {
I understand what you're saying. I put it in monitor because it uses the monitor client and monitor constants.

2020-12-09 17:37 UTC, KeionneDerousselle commented on src/steps/resource-manager/monitor/diagnostic-settings.ts
> +export async function fetchDiagnosticSettings(
I agree. That's a better name, and I will make that change.

2020-12-09 17:39 UTC, KeionneDerousselle commented on src/steps/resource-manager/monitor/diagnostic-settings.ts
> +  if (id && typeof id === 'string') {
I don't know that, in reality, it's ever undefined or an array, but typescript was complaining that it could be. I also figured we didn't want it to error out, but instead try to collect the other entities and relationships that it could.

2020-12-09 17:41 UTC, KeionneDerousselle commented on src/steps/resource-manager/monitor/__recordings__/iterateDiagnosticSettings_3260250107/recording.har
> +          "url": "https://management.azure.com/subscriptions?api-version=2016-06-01"
I'm not really sure. I don't think I specifically called that....is that something the endpoint does?

2020-12-09 17:41 UTC, KeionneDerousselle commented on src/steps/resource-manager/monitor/client.ts
> +      },
Ok

2020-12-09 17:56 UTC, ndowmon commented on src/steps/resource-manager/monitor/converters.ts
> +}
You don't have to worry about this comment. It's alright to create these two entities as you and @aiwilliams have discussed.

2020-12-09 18:14 UTC, ndowmon commented on src/steps/resource-manager/monitor/diagnostic-settings.ts
> +  if (id && typeof id === 'string') {
```typescript
(id as string)
```

2020-12-09 18:26 UTC, ndowmon commented on src/steps/resource-manager/monitor/diagnostic-settings.ts
> +
```typescript
let monitorClient: MonitorClient;

function getMonitorClient(config, logger) {
  if (!monitorClient) { 
    monitorClient = new MonitorClient(config, logger);
  } 
 return monitorClient;
}

// inside fetchDiagnosticSettings()...

  // const client = new MonitorClient(instance.config, logger);
  const client = getMonitorClient(instance.config, logger);

```

2020-12-09 19:00 UTC, ndowmon commented on src/steps/resource-manager/monitor/constants.ts
> +    sourceType: ANY_RESOURCE,
Can you please add docstrings on `ANY_SCOPE` and `ANY_RESOURCE` to describe the differences?

2020-12-10 19:43 UTC, ndowmon commented on terraform/monitor.tf
>    target_resource_id = azurerm_key_vault.j1dev_diag_set_key_vault[0].id
Can you just use the existing `azurerm_key_vault.j1dev` resource? If you check out `keyvault.tf` you'll see that it's an always-on resource (it does not have a `create_key_vault_resources` flag like the `create_monitor_diagnostic_settings` flag we see in this file).

2020-12-10 19:49 UTC, ndowmon commented on src/utils/diagnosticSettings.ts
>  import {
Nice refactor! Let's still look through it in a little more detail together but this looks better to me. One change I think would be nice is to change the filename from `diagnosticSettings.ts` to match the primary (only?) export from this file.

2020-12-10 22:47 UTC, ndowmon commented on terraform/monitor.tf
>    name                     = "j1devlogprofilestrgacct"
Shoot this also needs to use the `developerId` TF variable since it the `name` of a storage account must be globally unique. Sorry I missed this in the **Log Profile** PR. Can you update?

2020-12-11 19:06 UTC, ndowmon commented on src/steps/resource-manager/key-vault/index.ts
> +      MonitorRelationships.DIAGNOSTIC_METRIC_SETTING_USES_STORAGE_ACCOUNT,
Taking another look at this... it would be great if these could be exported as `diagnosticSettingsRelationshipsForResource` (an array of relationship metadata) from the `createDiagnosticSettingsEntitiesAndRelationshipsForResource` file. These same four relationships will show up _every_ time `createDiagnosticSettingsEntitiesAndRelationshipsForResource` is called in a step.

The same goes for `diagnosticSettingsEntitiesForResource`, which would be an array of entity metadata including `MonitorEntities.DIAGNOSTIC_LOG_SETTING` and `MonitorEntities.DIAGNOSTIC_METRIC_SETTING`.

2020-12-11 19:20 UTC, ndowmon commented on src/steps/resource-manager/monitor/client.ts
> +          const diagnosticSettings = response.value!;
What happens if you try to call this endpoint on the following:
1. The resourceUri for a resource that exists and _can_ have a diagnostic setting, but does not (such as a key vault that has not provisioned diagnostic settings)
1. The resourceUri for a resource that exists but can _not_ have diagnostic settings. (You could pick a resource you've deployed through terraform that does not match the list that Azure publishes: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/resource-logs-categories)
1. The resourceUri for a resource that does _not_ exist. E.g. `/subscriptions/40474ebe-55a2-4071-8fa8-b610acdd8e56/resourcegroups/j1dev_diag_set_resource_group/providers/microsoft.keyvault/vaults/J1_NON_EXISTENT_KEYVAULT`

I'm particularly concerned about the result of point 1, because we will be iterating every key vault after this PR is merged and we need to make sure the API response for key vaults without these configured diagnostic settings do not cause system errors.

2020-12-11 19:23 UTC, ndowmon reviewed
Hey @KeionneDerousselle thanks for the revisions. I did another review of the changes and noticed a few things I missed previously.

2020-12-11 20:29 UTC, ndowmon commented on src/steps/resource-manager/monitor/client.ts
> +          const diagnosticSettings = response.value!;
Per slack, Point 1 returns an empty array.

2020-12-11 20:32 UTC, ndowmon approved these changes
Thank you so much for the iterations @KeionneDerousselle!

2020-12-16 19:41 UTC, austinkelleher approved these changes

2020-12-17 14:49 UTC, merged