Add integration benefits
JupiterOne/graph-azure pull request #274
Opened 2021-04-01 19:14 UTC by jayson-jensen-pro

2021-04-02 17:01 UTC, mknoedel approved these changes

2021-04-02 20:44 UTC, aiwilliams approved these changes
Some recommendations, but nothing that should slow you down too much! Thanks so much.

2021-04-02 20:44 UTC, aiwilliams commented on docs/jupiterone.md
> +- Configure alerts to take action when the JupiterOne graph changes, or leverage existing alerts.
I like the "or leverage existing ...". Would be worthwhile I think to add to https://github.com/JupiterOne/integration-template/blob/master/docs/jupiterone.md.

2021-04-02 20:44 UTC, aiwilliams commented on docs/jupiterone.md
> +the Application (client) id, and the Application (client) secret with the correct permissions assigned.
We use https://github.com/typicode/husky to cause certain scripts to execute before creating creating a git commit, configured in each repository ([for example](https://github.com/JupiterOne/graph-azure/blob/master/husky.config.js)). That will run [a script in `package.json`](https://github.com/JupiterOne/graph-azure/blob/efa2c147cc78048e6278c24bbf35114b1fccbc7d/package.json#L27), which *should* include formatting these markdown files. When you get a chance, it would be good to get that working on your machine so that these are formatted.

In this case, the line exceeds the column length that we intend.

2021-04-02 20:44 UTC, aiwilliams commented on docs/jupiterone.md
> +- Monitor compliance against the Azure CIS Framework and other security
Should this be `Azure CIS Benchmarks framework` for ©️ reasons?

![Screen Shot 2021-04-02 at 4 42 36 PM](https://user-images.githubusercontent.com/2571/113452697-85139380-93d2-11eb-8f1d-234c8fc51687.png)

2021-04-05 14:38 UTC, jayson-jensen-pro commented on docs/jupiterone.md
> +- Configure alerts to take action when the JupiterOne graph changes, or leverage existing alerts.
@aiwilliams of course! https://github.com/JupiterOne/integration-template/pull/27

2021-04-05 16:16 UTC, aiwilliams submitted a review, later dismissed

2021-04-05 22:30 UTC, jayson-jensen-pro commented on docs/jupiterone.md
> +the Application (client) id, and the Application (client) secret with the correct permissions assigned.
Going to make edits in the UI, but will keep this in mind!

2021-04-05 23:46 UTC, aiwilliams requested changes
Looking good! One small fix to make.

2021-04-05 23:46 UTC, aiwilliams commented on docs/jupiterone.md
> +should only be anbled in one integration instance per Directory.
```suggestion
- Select the option **Ingest Active Directory** to ingest Directory information. This
  should only be enabled in one integration instance per Directory.
```

2021-04-09 20:26 UTC, aiwilliams approved these changes

2021-04-11 21:02 UTC, merged