INT-1776 - Add 8.3, 8.4 and 8.5 CIS benchmarks
JupiterOne/graph-azure pull request #437
Opened 2021-09-29 14:45 UTC by eXtremeX

**Note: this PR is rebased against the #435 PR - best if this is reviewed after #435.**

This PR adds the following (new) benchmarks:

- 8.3 Ensure that Resource Locks are set for mission-critical Azure resources (Manual)
- 8.4 Ensure the key vault is recoverable (Automated)
- 8.5 Enable role-based access control (RBAC) within Azure Kubernetes Services (Automated)

### Some notes:
1) This and #435 required the use of a newer data-model package otherwise we've been running into the following issue: _class: Secret not defined in J1/SDK_, this is the reason behind the `package.json` changes.
2) 8.3 is still missing the part where we are supposed to be building relationships between `{anyResource} -HAS-> lock`. We've checked the `listAtResourceGroupLevel()` method, it returns all the locks for both the resource group & any child resources.

![image](https://user-images.githubusercontent.com/8009142/135280481-b198612e-79ea-4252-962c-a15d815e5a97.png)

Maybe one approach is that we get the `_key` for the resource from the `id` property present on each element of `listAtResourceGroupLevel` response (e.g. the screenshot above). That way we can find the entity. The tricky part is going to be declaring all those relationships properly, but still can be done. Any ideas on how we should do that elegantly?

###  CHANGELOG.md
(to be added when this gets merged)
```
### Added

- Added support for ingesting the following **new** resources:

  | Service                    | Resource / Entity                  |
  | -------------------------- | ---------------------------------- |
  | Container Services Cluster | `azure_container_services_cluster` |
  | Resource Group Lock        | `azure_resource_group_lock`        |

- Added support for ingesting the following **new** relationships:

  | Source                 | \_class | Target                             |
  | ---------------------- | ------- | ---------------------------------- |
  | `azure_resource_group` | `HAS`   | `azure_container_services_cluster` |
  | `azure_resource_group` | `HAS`   | `azure_resource_group_lock`        |

- New properties added to resources:

  | Entity                             | Properties                |
  | ---------------------------------- | ------------------------- |
  | `azure_container_services_cluster` | `id`                      |
  | `azure_container_services_cluster` | `name`                    |
  | `azure_container_services_cluster` | `skuName`                 |
  | `azure_container_services_cluster` | `location`                |
  | `azure_container_services_cluster` | `principalId`             |
  | `azure_container_services_cluster` | `tenantId`                |
  | `azure_container_services_cluster` | `provisioningState`       |
  | `azure_container_services_cluster` | `maxAgentPools`           |
  | `azure_container_services_cluster` | `kubernetesVersion`       |
  | `azure_container_services_cluster` | `dnsPrefix`               |
  | `azure_container_services_cluster` | `fqdn`                    |
  | `azure_container_services_cluster` | `nodeResourceGroup`       |
  | `azure_container_services_cluster` | `enableRBAC`              |
  | `azure_container_services_cluster` | `enablePodSecurityPolicy` |
  | `azure_container_services_cluster` | `disableLocalAccounts`    |
  | `azure_container_services_cluster` | `webLink`                 |
  | `azure_resource_group_lock`        | `id`                      |
  | `azure_resource_group_lock`        | `name`                    |
  | `azure_resource_group_lock`        | `level`                   |
  | `azure_resource_group_lock`        | `notes`                   |
  | `azure_resource_group_lock`        | `type`                    |
  | `azure_keyvault_service`           | `enableSoftDelete`        |
  | `azure_keyvault_service`           | `enablePurgeProtection`   |
```

### J1QL Queries
- 8.3 Ensure that Resource Locks are set for mission critical Azure resources (Manual)
```
# GOOD CASE
find azure_resource_group that has azure_resource_group_lock with level = "CanNotDelete" or level = "ReadOnly"
   
# BAD CASE
find azure_resource_group that !has azure_resource_group_lock
OR
find azure_resource_group that has azure_resource_group_lock with level = "NotSpecified"
```
- 8.4 Ensure the key vault is recoverable (Automated)
```
# GOOD CASE
find azure_keyvault_service with enableSoftDelete = true and enablePurgeProtection = true
   
# BAD CASE
find azure_keyvault_service with enableSoftDelete != true and enablePurgeProtection != true
```
- 8.5 Enable role-based access control (RBAC) within Azure Kubernetes Services (Automated)
```
# GOOD CASE
find azure_container_services_cluster with enableRBAC = true
   
# BAD CASE
find azure_container_services_cluster with enableRBAC != true
```

Pinging @ndowmon @aiwilliams

2021-10-04 14:26 UTC, ndowmon requested changes
It looks like there is some missing pagination in these clients and there are some changes to tests that I would like to see. Also, since this creates two unrelated resources (and three unrelated questions), I think it might have been better served as two (or three) PRs.

On top of that, related to questions you posed in the PR description:

---

> 2. 8.3 is still missing the part where we are supposed to be building relationships between {anyResource} -HAS-> lock. We've checked the listAtResourceGroupLevel() method, it returns all the locks for both the resource group & any child resources.
>
> [image]
>
> Maybe one approach is that we get the _key for the resource from the id property present on each element of listAtResourceGroupLevel response (e.g. the screenshot above). That way we can find the entity. The tricky part is going to be declaring all those relationships properly, but still can be done. Any ideas on how we should do that elegantly?

This pattern is similar to what we had to do with the `Role Assignment to Scope Relationships` step. We used the `executeFirstSteps` array as a dependency for that step, forcing _all_ resource steps to finish before running this step & trying to build these relationships. See `dependsOn`:

```
  {
    id: steps.ROLE_ASSIGNMENT_SCOPES,
    name: 'Role Assignment to Scope Relationships',
    entities: [],
    relationships: [relationships.ROLE_ASSIGNMENT_ALLOWS_ANY_SCOPE],
    dependsOn: [
      steps.ROLE_ASSIGNMENTS,
      ...getResourceManagerSteps().executeFirstSteps,
    ],
    executionHandler: buildRoleAssignmentScopeRelationships,
  },
```

Then, since we know that all resources have already been gathered, we can safely use `await jobState.findEntity(roleAssignment.scope)` and create a direct relationship when the target entity exists in the job state (see `buildRoleAssignmentScopeRelationships`).

You should definitely make sure that this step is separate from ingesting resource locks. You should have two steps at the end, one that ingests resource locks, and another that iterates those resource locks, finds the target entity, and builds relationships. In other words, use the [Build Child Relationships step pattern](https://github.com/JupiterOne/sdk/blob/main/docs/integrations/step-patterns.md#build-child-relationships-step-pattern).

---

> ### J1QL Queries
> - 8.3 Ensure that Resource Locks are set for mission critical Azure resources (Manual)
> ```
> # GOOD CASE
> find azure_resource_group that has azure_resource_group_lock with level = "CanNotDelete" or level = "ReadOnly"
>    
> # BAD CASE
> find azure_resource_group that !has azure_resource_group_lock
> OR
> find azure_resource_group that has azure_resource_group_lock with level = "NotSpecified"
> ```

This CIS Benchmark actually does not have to do with `azure_resource_group` - in some way, the azure user ought to be marking some of their subscriptions, resource groups, or resources as **sensitive** (perhaps through tagging) and ensure that a lock exists on it. So the J1QL would be something like `FIND * with tag.SensitiveAzureResource = true THAT !HAS azure_resource_lock`. The query itself may need to be customer-specific.

2021-10-04 14:26 UTC, ndowmon commented on src/steps/resource-manager/container-services/constants.ts
> +  },
Actually, given that you're trying to answer the question: **8.5 Enable role-based access control (RBAC) within Azure Kubernetes Services (Automated)**, is this resource actually an `azure_kubernetes_cluster`?

2021-10-04 14:26 UTC, ndowmon commented on src/steps/resource-manager/key-vault/index.test.ts
> +  it('should collect an Azure Key Vault Key entity and relationships', async () => {
You can delete this altogether. Thanks for updating the style of this test.

2021-10-04 14:26 UTC, ndowmon commented on src/steps/resource-manager/key-vault/index.test.ts
> +      subscriptionId: '193f89dc-6225-4a80-bacb-96b32fbf6dd0',
See other comments re: not setting `directoryId` and `subscriptionId` directly.

2021-10-04 14:26 UTC, ndowmon commented on src/steps/resource-manager/resources/constants.ts
> +  resourceName: '[RM] Resource Group Lock',
This is a resource lock, not a resource group lock. It can be assigned to a subscription, resource group, or resource. FWIW, some azure documentation refers to this resource as an **Azure Management Lock**, but in the web console it's called **Resource Lock**.

2021-10-06 03:55 UTC, Dhaiwat10 commented on src/steps/resource-manager/container-services/client.ts
> +      }
I believe there was a mismatch in patterns here. I've changed the code to use the `iterateAllResources()` pattern. I'm also having a look at adding support for pagination if needed, thanks for pointing that out!

2021-10-06 03:56 UTC, Dhaiwat10 commented on src/steps/resource-manager/resources/index.test.ts
> +    name: 'resource-manager-step-groups',
I don't think so. I've reverted this change. 👍🏻

2021-10-06 03:57 UTC, Dhaiwat10 commented on src/steps/resource-manager/resources/index.test.ts
> +  };
Thanks for pointing this out, will do!

2021-11-02 19:59 UTC, ndowmon approved these changes

2021-11-02 19:59 UTC, ndowmon commented on jupiterone/questions/questions.yaml
> +        FIND * with tag.SensitiveAzureResource = true THAT HAS azure_resource_lock
We'll need to decide how to label certain resources as sensitive.

2021-11-02 20:20 UTC, ndowmon approved these changes

2021-11-02 20:20 UTC, merged