Azure enhancement dev
JupiterOne/graph-azure pull request #630
Opened 2024-03-27 05:43 UTC by poornima-metron

2024-04-07 12:36 UTC, suraj-metron commented
Changelog file is not updated. Please update

2024-04-07 12:50 UTC, suraj-metron requested changes

2024-04-08 05:12 UTC, poornima-metron commented on src/config.ts
> +  [INGESTION_SOURCE_IDS.APPLICATION_SECURITY_GROUP]: {
added for all services

2024-04-08 05:24 UTC, poornima-metron commented on src/index.ts
> +import { SynapseSteps } from './steps/resource-manager/synapse';
Kubernetes is already existing service which is container Service

2024-04-08 05:24 UTC, poornima-metron commented on src/steps/resource-manager/express-route/converters.ts
> +      source: {},
added undefined

2024-04-08 05:24 UTC, poornima-metron commented on src/steps/resource-manager/synapse/converter.ts
> +      source: {},
added undefined

2024-04-09 17:47 UTC, suraj-metron approved these changes

2024-04-11 05:56 UTC, merged

2024-05-13 13:29 UTC, j1-internal-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v7.0.0`](https://github.com/JupiterOne/graph-azure/releases/tag/v7.0.0) :rocket: