completed rolebinding step and relationship
JupiterOne/graph-azure pull request #635
Opened 2024-04-12 07:31 UTC by poornima-metron

2024-04-12 08:13 UTC, suraj-metron requested changes

2024-04-12 08:13 UTC, suraj-metron commented on src/steps/resource-manager/container-services/converters.ts
> +    throw new Error('Invalid id format');
Dont throw an error. Wrap the function in try catch. If there is any exception, just log it and return a default value or empty string maybe

2024-04-12 08:13 UTC, suraj-metron commented on src/steps/resource-manager/container-services/index.ts
> +            _key: `${rolebindingEntity._key}|IS|ClusterRole:${rolebindingEntity._key}`,
Use a function to return this value

2024-04-12 09:03 UTC, poornima-metron commented on src/steps/resource-manager/container-services/converters.ts
> +    throw new Error('Invalid id format');
Wrapped the function in try catch

2024-04-12 09:19 UTC, poornima-metron commented on src/steps/resource-manager/container-services/index.ts
> +            _key: `${rolebindingEntity._key}|IS|ClusterRole:${rolebindingEntity._key}`,
created function to generate key

2024-04-12 11:46 UTC, merged

2024-05-13 13:29 UTC, j1-internal-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v7.0.0`](https://github.com/JupiterOne/graph-azure/releases/tag/v7.0.0) :rocket: