access-group developed
JupiterOne/graph-azure pull request #642
Opened 2024-05-15 11:21 UTC by poornima-metron

2024-05-21 05:56 UTC, suraj-metron requested changes

2024-05-21 06:06 UTC, suraj-metron approved these changes

2024-05-22 07:22 UTC, Bharatkk-metron commented on src/steps/active-directory/index.ts
> +      details = userDetials;
Do we need a `details` array? can't we directly get userDetails[0], userDetails[1], userDetails[2], userDetails[3]?

2024-05-22 07:54 UTC, poornima-metron commented on src/steps/active-directory/index.ts
> +      details = userDetials;
fixed this , using userDetails

2024-05-22 07:54 UTC, poornima-metron commented on src/index.ts
> +
removed

2024-05-22 07:59 UTC, Bharatkk-metron approved these changes
Looks good to me.

2024-05-22 08:00 UTC, merged