Azure conditional access dev
JupiterOne/graph-azure pull request #652
Opened 2024-06-27 09:13 UTC by Bharatkk-metron

Miro Board Link: https://miro.com/app/board/uXjVNySkU7Q=/

Added entities: 

[AD] Conditional Access 
[AD] Conditional Access Authorization Context  
[AD] Conditional Access Named location       
[AD] Conditional Access Policy  
[AD] Conditional Access Template  

Added Relationships:

azure_conditional_access_policy **CONTAINS** azure_conditional_access_named_location
azure_conditional_access_policy` **ASSIGNED** azure_user                                     
azure_conditional_access_policy **ASSIGNED** azure_user_group                               
azure_conditional_access_service **HAS** azure_conditional_access_authorization_context
azure_conditional_access_servic **HAS** azure_conditional_access_policy
azure_conditional_access_service **HAS** azure_conditional_access_template

2024-06-27 09:33 UTC, suraj-metron requested changes

2024-06-27 09:33 UTC, suraj-metron commented on src/steps/active-directory/conditional-access-policy/constants.ts
> +// yarn start --step 'fetch-conditional-access,fetch-conditional-access-template,fetch-conditional-access-policy,fetch-conditional-access-named-location,fetch-conditional-access-auth-context,build-co
Do we need this comments here?

2024-06-27 09:33 UTC, suraj-metron commented on src/steps/active-directory/conditional-access-policy/entities/conditional-access-authorization-context.ts
> +  apiPermissions: ['Policy.Read.ConditionalAccess	'],
There is extra space here, not sure but this might cause some malfunction

2024-06-27 09:33 UTC, suraj-metron commented on src/steps/active-directory/conditional-access-policy/entities/conditional-access.ts
> +  dependsOn: [],
I hope we have verified the dependsOn for all entities. I see all of them are empty

2024-06-27 09:33 UTC, suraj-metron commented on src/steps/active-directory/conditional-access-policy/entities/test/conditional-access-authorization-context.test.ts
> +  100_000,
why this hardcoded value?

2024-06-27 09:33 UTC, suraj-metron commented on src/steps/active-directory/conditional-access-policy/entities/test/conditional-access-template.test.ts
> +  100_000,
lets move to constants

2024-06-27 09:36 UTC, Bharatkk-metron commented on src/steps/active-directory/conditional-access-policy/constants.ts
> +// yarn start --step 'fetch-conditional-access,fetch-conditional-access-template,fetch-conditional-access-policy,fetch-conditional-access-named-location,fetch-conditional-access-auth-context,build-co
This is useful to run a particular service.

2024-06-27 09:37 UTC, Bharatkk-metron commented on src/steps/active-directory/conditional-access-policy/entities/conditional-access.ts
> +  dependsOn: [],
yes. there is no dependency.

2024-06-27 10:51 UTC, suraj-metron submitted a review, later dismissed

2024-07-08 14:14 UTC, Gonzalo-Avalos-Ribas commented on src/steps/active-directory/conditional-access-policy/relationships/conditional-access-policy-assigned-azure-users.ts
> +          await jobState.iterateEntities(
Hmmm for each conditional access policy we are iterating all users and creating a new relationship, this could cause issues

2024-07-09 05:14 UTC, Bharatkk-metron commented on src/steps/active-directory/conditional-access-policy/relationships/conditional-access-policy-assigned-azure-users.ts
> +          await jobState.iterateEntities(
@Gonzalo-Avalos-Ribas  'All' states that the conditional access policy is assigned to all users. Would you like to have a relationship like this: ConditionalAccessPolicy Assigned All?"

2024-07-09 13:33 UTC, Gonzalo-Avalos-Ribas approved these changes

2024-07-09 13:33 UTC, merged

2024-07-09 13:37 UTC, j1-internal-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v7.2.0`](https://github.com/JupiterOne/graph-azure/releases/tag/v7.2.0) :rocket: