added tenantId property and updated sdk
JupiterOne/graph-azure pull request #665
Opened 2024-08-14 07:32 UTC by poornima-metron

2024-08-16 13:22 UTC, suraj-metron commented on CHANGELOG.md
Did we updated this file or it got automatically updated? I remember J1 team mentioned that this file will be automatically updated. Please correct me If I am wrong

2024-08-16 13:25 UTC, suraj-metron requested changes

2024-08-16 13:25 UTC, suraj-metron commented on CHANGELOG.md
> +# v7.8.2 (Fri Aug 16 2024)
Did we updated this file or it got automatically updated? I remember J1 team mentioned that this file will be automatically updated. Please correct me If I am wrong

2024-08-16 13:42 UTC, poornima-metron commented on CHANGELOG.md
> +# v7.8.2 (Fri Aug 16 2024)
we have updated it , i think the comments was for monorepo PR's

2024-08-28 19:27 UTC, Gonzalo-Avalos-Ribas commented
Closing in favor of https://github.com/JupiterOne/graph-azure/pull/671

2024-08-29 13:35 UTC, closed without merging